/** Public operation names used by the Supabase-backed client adapter. */
export const api = {
  analyze: {
    getCached: 'analyze.getCached',
    storeSync: 'analyze.storeSync',
    getPublicByToken: 'analyze.getPublicByToken',
    storeOne: 'analyze.storeOne',
    saveAnnotations: 'analyze.saveAnnotations',
  },
  bookProgress: {
    getBookProgress: 'bookProgress.getBookProgress',
    recordAttempt: 'bookProgress.recordAttempt',
    advanceCycle: 'bookProgress.advanceCycle',
    migrateLocalProgress: 'bookProgress.migrateLocalProgress',
    importLegacyWoodpecker: 'bookProgress.importLegacyWoodpecker',
  },
  users: {
    current: 'users.current',
    updateLanguage: 'users.updateLanguage',
    updateAccounts: 'users.updateAccounts',
  },
  courses: {
    list: 'courses.list',
    get: 'courses.get',
    listChapters: 'courses.listChapters',
    getTree: 'courses.getTree',
    getChapterTree: 'courses.getChapterTree',
    create: 'courses.create',
    ensureImported: 'courses.ensureImported',
    remove: 'courses.remove',
    rename: 'courses.rename',
    renameChapter: 'courses.renameChapter',
    reorderChapters: 'courses.reorderChapters',
    deleteChapter: 'courses.deleteChapter',
    setLineInfoOnly: 'courses.setLineInfoOnly',
    setSharing: 'courses.setSharing',
    getPublicByToken: 'courses.getPublicByToken',
    getPublicChapterTree: 'courses.getPublicChapterTree',
    updateAnnotation: 'courses.updateAnnotation',
  },
  import: {
    listCourseImports: 'import.listCourseImports',
    createCourseImport: 'import.createCourseImport',
    importTreeIntoChapter: 'import.importTreeIntoChapter',
    importBundle: 'import.importBundle',
  },
  repertoires: {
    list: 'repertoires.list',
    get: 'repertoires.get',
    create: 'repertoires.create',
    remove: 'repertoires.remove',
    rename: 'repertoires.rename',
    addCourse: 'repertoires.addCourse',
    removeCourse: 'repertoires.removeCourse',
    setChoice: 'repertoires.setChoice',
    clearChoice: 'repertoires.clearChoice',
    listCourses: 'repertoires.listCourses',
    loadTree: 'repertoires.loadTree',
    getPublicByToken: 'repertoires.getPublicByToken',
  },
  sharing: {
    getSettings: 'sharing.getSettings',
    setLinkAccess: 'sharing.setLinkAccess',
    rotateLink: 'sharing.rotateLink',
    upsertInvitation: 'sharing.upsertInvitation',
    removeInvitation: 'sharing.removeInvitation',
    transferOwnership: 'sharing.transferOwnership',
    listSharedWithMe: 'sharing.listSharedWithMe',
    listSharedCourses: 'sharing.listSharedCourses',
    listSharedRepertoires: 'sharing.listSharedRepertoires',
    listSharedAnalysis: 'sharing.listSharedAnalysis',
    listMySharedAnalysis: 'sharing.listMySharedAnalysis',
    resolveToken: 'sharing.resolveToken',
  },
  training: {
    ensureCards: 'training.ensureCards',
    getTrainingLines: 'training.getTrainingLines',
    getCourseLineStatuses: 'training.getCourseLineStatuses',
    getCachedLineStats: 'training.getCachedLineStats',
    ensureCounterSnapshot: 'training.ensureCounterSnapshot',
    getCourseLineProgress: 'training.getCourseLineProgress',
    submitLineRatings: 'training.submitLineRatings',
    markInfoLineViewed: 'training.markInfoLineViewed',
    getTrainingStats: 'training.getTrainingStats',
    exportReviewData: 'training.exportReviewData',
  },
} as const;
