-- RepDrill's Supabase target schema.
--
-- WorkOS is the identity provider.  `users.id` is RepDrill's internal UUID;
-- `workos_user_id` is the stable external identity and `legacy_convex_id`
-- keeps the Convex -> Supabase migration resumable and auditable.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  workos_user_id text unique,
  legacy_convex_id text unique,
  name text,
  image text,
  email text,
  email_verification_time timestamptz,
  phone text,
  phone_verification_time timestamptz,
  is_anonymous boolean not null default false,
  lichess_username text,
  chesscom_username text,
  language text not null default 'en' check (language in ('en', 'uk')),
  last_analyze_sync_lichess_at timestamptz,
  last_analyze_sync_chesscom_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists users_email_lower_idx on public.users (lower(email)) where email is not null;

-- Convex's internal auth tables contain provider/session records which cannot
-- be imported as WorkOS credentials. Preserve them as immutable JSON so the
-- migration is lossless and auditable, while WorkOS owns future sessions.
create table if not exists public.legacy_auth_documents (
  id bigint generated by default as identity primary key,
  source_table text not null,
  source_id text not null,
  payload jsonb not null,
  imported_at timestamptz not null default now(),
  unique (source_table, source_id)
);

create table if not exists public.legacy_id_map (
  source_table text not null,
  source_id text not null,
  destination_id uuid not null,
  migrated_at timestamptz not null default now(),
  primary key (source_table, source_id)
);

create table if not exists public.legacy_storage_documents (
  id bigint generated by default as identity primary key,
  storage_id text not null unique,
  content_type text,
  size_bytes bigint,
  object_path text,
  payload jsonb not null,
  imported_at timestamptz not null default now()
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  color text not null check (color in ('white', 'black')),
  description text,
  source_course_id text,
  source_url text,
  is_public boolean not null default false,
  share_token text,
  last_chapter_reorder_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.share_links (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  owner_id uuid not null references public.users(id) on delete cascade,
  resource_type text not null check (resource_type in ('course', 'repertoire', 'analysis')),
  resource_id text not null,
  scope_type text check (scope_type in ('resource', 'course', 'chapter', 'line')),
  scope_id text,
  scope_label text,
  token text,
  access text not null check (access in ('none', 'view', 'copy', 'collaborate')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, resource_type, resource_id, scope_type, scope_id),
  unique (token)
);

create table if not exists public.share_invitations (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  owner_id uuid not null references public.users(id) on delete cascade,
  resource_type text not null check (resource_type in ('course', 'repertoire', 'analysis')),
  resource_id text not null,
  scope_type text check (scope_type in ('resource', 'course', 'chapter', 'line')),
  scope_id text,
  scope_label text,
  email text not null,
  access text not null check (access in ('view', 'copy', 'collaborate')),
  notify boolean not null default true,
  message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chapters (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  course_id uuid not null references public.courses(id) on delete cascade,
  name text not null,
  chapter_type text not null default 'training' check (chapter_type in ('training', 'info_only')),
  sort_order integer not null,
  description text,
  source_chapter_id text,
  source_file text,
  created_at timestamptz not null default now()
);

create table if not exists public.chapter_line_settings (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  chapter_id uuid references public.chapters(id) on delete cascade,
  source_chapter_id text,
  line_key text not null,
  info_only boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (chapter_id, line_key)
);

create table if not exists public.info_line_views (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id uuid not null references public.users(id) on delete cascade,
  chapter_id uuid not null references public.chapters(id) on delete cascade,
  line_key text not null,
  viewed_at timestamptz not null,
  unique (user_id, chapter_id, line_key)
);

create table if not exists public.book_progress (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id uuid not null references public.users(id) on delete cascade,
  book_key text not null check (book_key in ('woodpecker-method', 'woodpecker-method-2')),
  cycle integer not null,
  position integer not null,
  set_size integer not null,
  solved_count integer not null default 0,
  missed_count integer not null default 0,
  unresolved_missed_count integer not null default 0,
  attempt_count integer not null default 0,
  started_at timestamptz,
  source_marker text,
  last_imported_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, book_key)
);

create table if not exists public.book_puzzle_progress (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id uuid not null references public.users(id) on delete cascade,
  book_key text not null check (book_key in ('woodpecker-method', 'woodpecker-method-2')),
  cycle integer not null,
  puzzle integer not null,
  solved boolean not null default false,
  missed boolean not null default false,
  attempt_count integer not null default 0,
  best_success_time_ms integer,
  last_time_ms integer,
  last_success boolean not null default false,
  last_attempt_at timestamptz not null,
  source_marker text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, book_key, cycle, puzzle)
);

create table if not exists public.book_puzzle_attempts (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id uuid not null references public.users(id) on delete cascade,
  book_key text not null check (book_key in ('woodpecker-method', 'woodpecker-method-2')),
  cycle integer not null,
  puzzle integer not null,
  attempt integer not null,
  success boolean not null,
  duration_ms integer,
  recorded_at timestamptz not null,
  source text not null check (source in ('native', 'legacy_import')),
  source_marker text not null,
  source_attempt_key text not null,
  import_id uuid,
  unique (user_id, book_key, source_attempt_key)
);

create table if not exists public.book_progress_imports (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id uuid not null references public.users(id) on delete cascade,
  book_key text not null check (book_key in ('woodpecker-method', 'woodpecker-method-2')),
  kind text not null check (kind in ('legacy_csv', 'local_storage')),
  source_marker text not null,
  idempotency_key text not null,
  source_record_count integer not null,
  imported_attempt_count integer not null,
  cycle integer not null,
  position integer not null,
  set_size integer not null,
  solved_count integer not null,
  missed_count integer not null,
  created_at timestamptz not null default now(),
  completed_at timestamptz not null,
  unique (user_id, book_key, source_marker)
);

create table if not exists public.repertoires (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.positions (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id uuid not null references public.users(id) on delete cascade,
  fen text not null,
  annotation text,
  unique (user_id, fen)
);

create table if not exists public.repertoire_courses (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  repertoire_id uuid not null references public.repertoires(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  sort_order integer not null,
  unique (repertoire_id, course_id)
);

create table if not exists public.repertoire_choices (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  repertoire_id uuid not null references public.repertoires(id) on delete cascade,
  position_id uuid not null references public.positions(id) on delete cascade,
  preferred_move_id uuid not null,
  unique (repertoire_id, position_id)
);

create table if not exists public.moves (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  chapter_id uuid not null references public.chapters(id) on delete cascade,
  parent_position_id uuid not null references public.positions(id),
  child_position_id uuid not null references public.positions(id),
  san text not null,
  uci text not null,
  move_number integer not null,
  color_to_move text not null check (color_to_move in ('white', 'black')),
  is_main_line boolean not null default false,
  move_type text not null check (move_type in ('repertoire', 'opponent', 'alternative')),
  sort_order integer not null,
  comment text,
  annotations jsonb,
  unique (chapter_id, parent_position_id, uci, move_type)
);

do $$
begin
  alter table public.repertoire_choices
    add constraint repertoire_choices_preferred_move_fk
    foreign key (preferred_move_id) references public.moves(id) on delete cascade;
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.course_imports (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  course_id uuid references public.courses(id) on delete cascade,
  source_course_id text,
  user_id uuid not null references public.users(id) on delete cascade,
  status text not null check (status in ('queued', 'processing', 'done', 'failed')),
  total_chapters integer not null,
  completed_chapters integer not null default 0,
  failed_chapters integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_import_chapters (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  import_id uuid not null references public.course_imports(id) on delete cascade,
  course_id uuid references public.courses(id) on delete cascade,
  source_course_id text,
  user_id uuid not null references public.users(id) on delete cascade,
  chapter_name text not null,
  chapter_type text not null check (chapter_type in ('training', 'info_only')),
  sort_order integer not null,
  course_color text not null check (course_color in ('white', 'black')),
  root_fen text not null,
  source_chapter_id text,
  source_file text,
  status text not null check (status in ('queued', 'processing', 'done', 'failed')),
  total_moves integer not null,
  processed_moves integer not null default 0,
  move_chunk_count integer not null,
  created_chapter_id uuid references public.chapters(id),
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_import_move_chunks (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  chapter_import_id uuid not null references public.course_import_chapters(id) on delete cascade,
  chunk_index integer not null,
  moves jsonb not null,
  created_at timestamptz not null default now(),
  unique (chapter_import_id, chunk_index)
);

create table if not exists public.review_cards (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id uuid not null references public.users(id) on delete cascade,
  move_id uuid not null references public.moves(id) on delete cascade,
  due timestamptz not null,
  stability double precision not null,
  difficulty double precision not null,
  elapsed_days double precision not null,
  scheduled_days double precision not null,
  reps integer not null,
  lapses integer not null,
  state integer not null,
  last_review timestamptz,
  unique (user_id, move_id)
);

create table if not exists public.review_logs (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  card_id uuid not null references public.review_cards(id) on delete cascade,
  rating integer not null,
  response_time_ms integer,
  reviewed_at timestamptz not null,
  prev_stability double precision,
  prev_difficulty double precision,
  prev_state integer
);

create table if not exists public.analyzed_games (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id uuid not null references public.users(id) on delete cascade,
  source text not null check (source in ('lichess', 'chesscom')),
  game_id text not null,
  url text,
  white_username text not null,
  black_username text not null,
  result text not null check (result in ('1-0', '0-1', '1/2-1/2', '*')),
  played_at timestamptz not null,
  opening text,
  time_control text,
  pgn text not null,
  played_as text not null check (played_as in ('white', 'black')),
  deviation_kind text not null check (deviation_kind in ('in_book', 'left_book', 'no_repertoire_for_color', 'parse_error')),
  deviation_move_number integer,
  deviation_ply integer,
  played_san text,
  expected_sans jsonb,
  deviation_fen text,
  total_plies integer not null,
  deviation_position_id uuid references public.positions(id),
  analyzed_at timestamptz not null,
  annotations text
);

-- Read-optimized counters. They are deliberately not computed by page loads.
create table if not exists public.counter_snapshots (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  course_id uuid references public.courses(id) on delete cascade,
  total_lines integer not null default 0,
  learned_lines integer not null default 0,
  due_lines integer not null default 0,
  new_lines integer not null default 0,
  computed_at timestamptz not null default now(),
  refresh_requested_at timestamptz,
  unique (user_id, course_id)
);

create table if not exists public.counter_refresh_jobs (
  user_id uuid primary key references public.users(id) on delete cascade,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  status text not null default 'queued' check (status in ('queued', 'running', 'done', 'failed')),
  error text
);

create index if not exists courses_user_idx on public.courses(user_id);
create index if not exists chapters_course_idx on public.chapters(course_id, sort_order);
create index if not exists moves_chapter_idx on public.moves(chapter_id);
create index if not exists review_cards_user_due_idx on public.review_cards(user_id, due);
create index if not exists review_logs_card_reviewed_idx on public.review_logs(card_id, reviewed_at);
create index if not exists counter_snapshots_user_idx on public.counter_snapshots(user_id, course_id);

-- The application uses WorkOS sessions, so its DB role is server-only. Keep
-- this explicit so a later Supabase client/RLS rollout cannot accidentally
-- expose all rows to an anon key.
alter table public.users enable row level security;
alter table public.courses enable row level security;
alter table public.review_cards enable row level security;
alter table public.counter_snapshots enable row level security;

create or replace function public.refresh_counter_snapshots(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.counter_snapshots where user_id = p_user_id;

  insert into public.counter_snapshots (user_id, course_id, total_lines, learned_lines, due_lines, new_lines, computed_at)
  select
    p_user_id,
    c.id,
    count(m.id)::integer,
    count(rc.id) filter (where rc.last_review is not null or rc.state <> 0)::integer,
    count(rc.id) filter (where rc.due <= now() and (rc.last_review is not null or rc.state <> 0))::integer,
    (count(m.id) - count(rc.id) filter (where rc.last_review is not null or rc.state <> 0))::integer,
    now()
  from public.courses c
  join public.chapters ch on ch.course_id = c.id
  join public.moves m on m.chapter_id = ch.id and m.move_type = 'repertoire'
  left join public.review_cards rc on rc.move_id = m.id and rc.user_id = p_user_id
  where c.user_id = p_user_id
  group by c.id;

  insert into public.counter_snapshots (user_id, course_id, total_lines, learned_lines, due_lines, new_lines, computed_at)
  select
    p_user_id,
    null,
    coalesce(sum(total_lines), 0)::integer,
    coalesce(sum(learned_lines), 0)::integer,
    coalesce(sum(due_lines), 0)::integer,
    coalesce(sum(new_lines), 0)::integer,
    now()
  from public.counter_snapshots
  where user_id = p_user_id and course_id is not null;
end;
$$;
